server:
  port: 8083
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 10080m # 1 week
  forward-headers-strategy: native

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://fov.ee/login/oauth2/code/google"
            scope:
              - email
              - profile
  application:
    name: auth
  redirect:
    uri: ${spring.security.oauth2.client.registration.google.redirect-uri}
  thymeleaf:
    cache: false
  data:
    redis:
      host: redis
      port: 6379
  session:
    store-type: redis

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    ee.tenman.auth: DEBUG
