redirect:
  url: ${REDIRECT_URI:YOUR_REDIRECT_URI}

allowed:
  emails: ${ALLOWED_EMAILS:YOUR_ALLOWED_EMAILS}

server:
  port: 8083
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      store-type: redis
      redis:
        namespace: spring:session  # Optional: defines a namespace for session keys
      cookie:
        max-age: 604800 # 7 days in seconds
        http-only: true
        secure: true
  forward-headers-strategy: native

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
  application:
    name: auth
  thymeleaf:
    cache: false
  data:
    redis:
      host: redis
      port: 6379
  session:
    store-type: redis

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    ee.tenman.auth: DEBUG
