name: Build & Test

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  DOCKER_IMAGE: ktenman/auth
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:

  build_and_push:
    name: 🔨 Build and push
    needs: [ test ]
    if: github.ref == 'refs/heads/main' && github.event_name != 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1
      - uses: docker/setup-buildx-action@v3.6.0
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          platforms: linux/amd64, linux/arm64/v8
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
  test:
    name: 🧪 Test with Gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
      - name: Run Gradle test
        run: ./gradlew test --info -x bootJar
      - uses: actions/upload-artifact@v4.3.5
        if: always()
        with:
          name: ${{ format('Test reports and screenshots ({0})', matrix.test-type) }}
          path: build/reports/tests

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    needs: [ test ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
